[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidateSet("cpu", "cuda")]
    [string]$Target,

    [string]$Venv = ".venv-minicpm-torch280"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$venvPath = if ([System.IO.Path]::IsPathRooted($Venv)) {
    $Venv
} else {
    Join-Path $repoRoot $Venv
}
$python = Join-Path $venvPath "Scripts/python.exe"
if (-not (Test-Path -LiteralPath $python -PathType Leaf)) {
    throw "Virtual environment Python not found: $python"
}

$probe = @'
import json
import platform
import sys

import torch

print(json.dumps({
    "platform": sys.platform,
    "python": platform.python_version(),
    "torch": torch.__version__,
    "torch_cuda": torch.version.cuda,
}))
'@
$probeJson = ($probe | & $python -) | ConvertFrom-Json
if ($LASTEXITCODE -ne 0) {
    throw "Could not inspect the Python environment."
}
if ($probeJson.platform -ne "win32") {
    throw "Windows lock files must be generated on Windows, not $($probeJson.platform)."
}
if ($probeJson.python -ne "3.11.9") {
    throw "Expected Python 3.11.9, found $($probeJson.python)."
}
if ($Target -eq "cuda") {
    if ($probeJson.torch -ne "2.8.0+cu128" -or $probeJson.torch_cuda -ne "12.8") {
        throw "CUDA lock requires torch 2.8.0+cu128 with torch CUDA 12.8."
    }
    & (Join-Path $PSScriptRoot "verify_minicpm_env.ps1") -Venv $venvPath
    if ($LASTEXITCODE -ne 0) {
        throw "MiniCPM CUDA environment verification failed."
    }
    $pytorchIndex = "https://download.pytorch.org/whl/cu128"
} else {
    if ($null -ne $probeJson.torch_cuda) {
        throw "CPU lock requires a CPU-only PyTorch build; found CUDA $($probeJson.torch_cuda)."
    }
    $pytorchIndex = "https://download.pytorch.org/whl/cpu"
}

& $python -m pip check
if ($LASTEXITCODE -ne 0) {
    throw "pip check found an inconsistent environment."
}
$freeze = @(
    & $python -m pip freeze --all --exclude-editable |
        Where-Object {
            $_ -notmatch "^(?i:auto[-_]gptq|human[-_]attributes[-_]detector)(==|\s@)"
        }
)
if ($LASTEXITCODE -ne 0 -or $freeze.Count -eq 0) {
    throw "Could not freeze the environment."
}
foreach ($line in $freeze) {
    if ($line -match "\s@\s(file:|git\+)" -or $line -match "^-e\s") {
        throw "Non-portable requirement in pip freeze: $line"
    }
    if ($line -notmatch "^[A-Za-z0-9_.-]+==[^\s]+$") {
        throw "Requirement is not an exact version pin: $line"
    }
}
$packageNames = @(
    $freeze | ForEach-Object {
        (($_ -split "==", 2)[0]).ToLowerInvariant().Replace("_", "-")
    }
)
if ($Target -eq "cuda") {
    foreach ($required in @("torch", "torchvision", "torchaudio", "onnxruntime-gpu")) {
        if ($required -notin $packageNames) {
            throw "CUDA lock is missing required package: $required"
        }
    }
    if ("onnxruntime" -in $packageNames) {
        throw "CUDA lock must not contain the CPU onnxruntime package."
    }
} else {
    foreach ($required in @("torch", "torchvision", "onnxruntime")) {
        if ($required -notin $packageNames) {
            throw "CPU lock is missing required package: $required"
        }
    }
    if ("onnxruntime-gpu" -in $packageNames) {
        throw "CPU lock must not contain onnxruntime-gpu."
    }
}

$baseline = Get-Content `
    -LiteralPath (Join-Path $repoRoot "reproducibility/windows-cuda-baseline.json") `
    -Raw | ConvertFrom-Json
$versions = @{}
foreach ($line in $freeze) {
    $parts = $line -split "==", 2
    $versions[$parts[0].ToLowerInvariant().Replace("_", "-")] = $parts[1]
}
if ($Target -eq "cuda") {
    $expectedOrt = [string]$baseline.onnxruntime.cuda_version
    if ($versions["onnxruntime-gpu"] -ne $expectedOrt) {
        throw (
            "CUDA lock requires onnxruntime-gpu==$expectedOrt; found " +
            "$($versions['onnxruntime-gpu'])."
        )
    }
} else {
    $expectedOrt = [string]$baseline.onnxruntime.cpu_version
    if ($versions["onnxruntime"] -ne $expectedOrt) {
        throw "CPU lock requires onnxruntime==$expectedOrt; found $($versions['onnxruntime'])."
    }
}
$header = @(
    "# Generated by scripts/export_windows_lock.ps1 from a verified Windows environment.",
    "# Python: $($probeJson.python)",
    "# Target: $Target"
)
if ($Target -eq "cuda") {
    $header += "# AutoGPTQ is installed separately from commit $($baseline.autogptq.commit)."
} else {
    $header += "# MiniCPM INT4 and AutoGPTQ are intentionally absent from the CPU environment."
}
$header += "--extra-index-url $pytorchIndex"
$lockDir = Join-Path $repoRoot "requirements/locks"
New-Item -ItemType Directory -Path $lockDir -Force | Out-Null
$lockPath = Join-Path $lockDir "windows-$Target-py311.lock.txt"
$payload = (@($header + $freeze) -join "`n") + "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($lockPath, $payload, $utf8NoBom)

Write-Host "Wrote $($freeze.Count) exact package pins to $lockPath"
